### ISSUE TITLE
Set up the server with Debian

### ISSUE THREAD

**Issue by Gabriel-Chen** [threestone-analytics/jamxio#7]
- [x] set up the Debian System
- [x] make sure the network port forwarding is working
- [ ] Setup nginx or apache
- [ ] Database
- [ ] set up Twitter & SMS api
- [ ] retrieve data to test api working (200 each)
- [ ] make sure all the data are mapped properly

**Comment by pesap** [comment]
@itisbenjamin Do you have any updates from Diego?

**Comment by itisbenjamin** [comment]
Nope, feels like he completely forgot 🙃

**Comment by pesap** [comment]
I included more task to do. I will look at them.
